//PRODUCTOS
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';

//USUARIOS
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';

//VENTAS
export const OBTENER_VENTAS = 'OBTENER_VENTAS';

//ALERTAS
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const CERRAR_ALERTA = 'CERRAR_ALERTA'
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PRODUCTO_NO_EXISTE = 'PRODUCTO_NO_EXISTE';
export const FORMULARIO_PRODUCTOS_VACIO = 'FORMULARIO_PRODUCTOS_VACIO';