//PRODUCTOS
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const CERRAR_ALERTA = 'CERRAR_ALERTA'
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';

//USUARIOS
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS';

//VENTAS
export const OBTENER_VENTAS = 'OBTENER_VENTAS';